apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: {{ .Values.telemetry.tracing.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  tracing:
    - providers:
        {{- toYaml .Values.telemetry.tracing.providers | nindent 8 }}
      randomSamplingPercentage: {{ .Values.telemetry.tracing.randomSamplingPercentage }}
      customTags:
        {{- toYaml .Values.telemetry.tracing.customTags | nindent 8 }}