apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: muffin-telemetry
  namespace: default
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - match:
            metric: REQUEST_COUNT
            mode: CLIENT_AND_SERVER
          tagOverrides:
            request_protocol:
              operation: UPSERT
              value: "%PROTOCOL%"
            app_name:
              operation: UPSERT
              value: "muffin-wallet"
        - match:
            metric: REQUEST_DURATION
            mode: CLIENT_AND_SERVER
        - match:
            metric: REQUEST_SIZE
            mode: CLIENT_AND_SERVER
        - match:
            metric: RESPONSE_SIZE
            mode: CLIENT_AND_SERVER
        - match:
            metric: TCP_OPENED_CONNECTIONS
            mode: CLIENT_AND_SERVER
        - match:
            metric: TCP_CLOSED_CONNECTIONS
            mode: CLIENT_AND_SERVER