apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: muffin-tracing
  namespace: default
spec:
  tracing:
    - providers:
        - name: "jaeger"
      randomSamplingPercentage: 100.0
      customTags:
        application:
          literal:
            value: "muffin-system"
        environment:
          environment:
            name: "ENV"
            defaultValue: "development"